"""Type stubs for the native `_wavetrace` extension (Phase 1 core types)."""

from typing import Optional

import numpy as np
import numpy.typing as npt

class WaveTraceError(Exception): ...
class FrameError(WaveTraceError): ...

class CsiFrame:
    def __init__(self, num_antennas: int, num_subcarriers: int) -> None: ...
    @property
    def num_antennas(self) -> int: ...
    @property
    def num_subcarriers(self) -> int: ...
    @property
    def size(self) -> int: ...
    timestamp: float
    node_id: int
    def reshape(self, num_antennas: int, num_subcarriers: int) -> None: ...
    @property
    def grid(self) -> npt.NDArray[np.complex64]:
        """Zero-copy writable view, shape (num_antennas, num_subcarriers)."""
        ...

class FrameParser:
    def __init__(self, num_antennas: int, num_subcarriers: int) -> None: ...
    @property
    def num_antennas(self) -> int: ...
    @property
    def num_subcarriers(self) -> int: ...
    def parse(
        self, raw: npt.NDArray[np.uint8], timestamp: float = 0.0, node_id: int = -1
    ) -> CsiFrame:
        """Decode one raw int8 [imag,real] frame into the reused CsiFrame (same object each call)."""
        ...

class NodeAggregator:
    def __init__(self) -> None: ...
    def submit(self, frame: CsiFrame) -> None: ...
    @property
    def num_nodes(self) -> int: ...
    def synced(self, tolerance: float) -> list[CsiFrame]: ...

def conjugate_multiply(in_frame: CsiFrame, out_frame: CsiFrame) -> None:
    """Geometry-adaptive conjugate multiply (cancels CFO/SFO); out_frame is reshaped + filled."""
    ...

def hampel(window: npt.NDArray[np.float32], current: float, k: float = 5.0) -> float:
    """Median if `current` is an outlier vs `window` (k*1.4826*MAD), else `current`."""
    ...

def unwrap_step(cur_wrapped: float, prev_wrapped: float, prev_unwrapped: float) -> float: ...

def coefficient_of_variation(amplitudes: npt.NDArray[np.float32]) -> float:
    """Gain-invariant variability sigma/mu; CV(k*A) == CV(A)."""
    ...

def nbvi_scores(amp: npt.NDArray[np.float32], alpha: float = 0.75) -> list[float]:
    """Per-subcarrier NBVI over a baseline (frames x subcarriers) amplitude matrix."""
    ...

def select_subcarriers_nbvi(
    amp: npt.NDArray[np.float32],
    alpha: float = 0.75,
    max_subcarriers: int = 12,
    noise_gate_percentile: float = 0.15,
) -> list[int]:
    """Up to max_subcarriers non-consecutive informative subcarrier indices (offline)."""
    ...

class GainLock:
    def __init__(self, baseline_packets: int = 300) -> None: ...
    def observe(self, frame: CsiFrame) -> None: ...
    def finalize(self) -> None: ...
    def apply(self, frame: CsiFrame) -> None:
        """Rescale the frame's amplitudes to the locked reference, in place (phase preserved)."""
        ...
    @property
    def observed(self) -> int: ...
    @property
    def ready(self) -> bool: ...
    @property
    def locked(self) -> bool: ...
    @property
    def reference_scale(self) -> float: ...

class Preprocessor:
    def __init__(
        self,
        num_antennas: int,
        num_subcarriers: int,
        hampel_window: int = 7,
        hampel_k: float = 5.0,
        normalize_alpha: float = 0.1,
    ) -> None: ...
    @property
    def out_rows(self) -> int: ...
    @property
    def out_cols(self) -> int: ...
    def reset(self) -> None: ...
    def process(self, frame: CsiFrame) -> npt.NDArray[np.float32]:
        """One frame -> drift-free differential-phase grid (zero-copy view, same buffer each call)."""
        ...

def fft(x: npt.NDArray[np.complex64]) -> npt.NDArray[np.complex64]:
    """Radix-2 forward FFT of a power-of-two complex64 array."""
    ...

def nine_features(window: npt.NDArray[np.float32]) -> list[float]:
    """REFERENCE §2.9 nine features [mean,std,max,min,IQR,skew,lag1,MAD,WL] over one window."""
    ...

def power_spectrum(x: npt.NDArray[np.float32], nfft: int = 0) -> npt.NDArray[np.float32]:
    """PSD (detrend + Hann + zero-pad to nfft) over nfft/2+1 bins; nfft=0 -> nextPow2(max(n,64))."""
    ...

def doppler_features(
    x: npt.NDArray[np.float32], fs: float, f_hi: float = 2.0, nfft: int = 0
) -> tuple[float, float]:
    """Doppler (max_shift_hz, spread_hz) from the PSD of a series (f_d = 2v/lambda)."""
    ...

class FeatureExtractor:
    def __init__(self, num_series: int, window: int, hop: int) -> None: ...
    @property
    def num_series(self) -> int: ...
    @property
    def window(self) -> int: ...
    @property
    def hop(self) -> int: ...
    @property
    def output_size(self) -> int: ...
    def reset(self) -> None: ...
    def push(self, values: npt.NDArray[np.float32]) -> bool:
        """Push one frame's num_series values; True when a feature vector was emitted."""
        ...
    @property
    def features(self) -> npt.NDArray[np.float32]:
        """Zero-copy view of the latest emitted vector (length 9*num_series, reused each emit)."""
        ...

class SpectrogramBuilder:
    def __init__(self, num_subcarriers: int, time_steps: int, hop: int) -> None: ...
    @property
    def num_subcarriers(self) -> int: ...
    @property
    def time_steps(self) -> int: ...
    @property
    def hop(self) -> int: ...
    def reset(self) -> None: ...
    def push(self, values: npt.NDArray[np.float32]) -> bool:
        """Push one frame's num_subcarriers values; True when an image was emitted."""
        ...
    @property
    def image(self) -> npt.NDArray[np.float32]:
        """Zero-copy view of the latest emitted (num_subcarriers x time_steps) image."""
        ...

class RecognitionResult:
    def __init__(self) -> None: ...
    class_id: int
    confidence: float
    timestamp: float
    bbox: Optional[list[float]]  # 4 elements (x, y, w, h); set from any 4-sequence
    keypoints: list[float]

class Label:
    def __init__(self) -> None: ...
    class_id: int
    name: str
    timestamp: float
    bbox: Optional[list[float]]  # 4 elements (x, y, w, h); set from any 4-sequence
    keypoints: list[float]
